version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: vyahanbolt
      POSTGRES_USER: vyahanboltuser
      POSTGRES_PASSWORD: vyahanboltpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5789:5432"

  redis:
    image: redis:7
    ports:
      - "6789:6379"

volumes:
  postgres_data: